### ISSUE TITLE
Dropping PHP < 8 versions not really forthcoming

### ISSUE THREAD

**Issue by finwe** [consistence-community/consistence-doctrine#4]
Why drop PHP 7, when 7.4 is going to be supported for another year? And, why drop it in a patch version?

**Comment by mhujer** [comment]
@finwe Hi! I have very little time which I can dedicate to maintaining the libraries, so I'm usually fast to drop support for older dependencies, sorry about that.

The previous versions of the library are still available, so the Composer should choose the latest which is available for the PHP version you are running. Is there some issue with that?

**Comment by finwe** [comment]
I understand, though I do not agree. There is an issue when new features and fixes are added, they are not available in older versions. I just ran into this when preparing a pull request and wanted to clarify PHP support first before continuing.

I am willing to lend a hand in helping support at least PHP 7.4, if there is an agreement. Otherwise, I will have to resort to maintaining my own fork, which is not ideal in other ways.

**Comment by mhujer** [comment]
@finwe I just re-added PHP 7.4 support and tagged a new version of the library. There were no issues with re-adding PHP 7.4 support, but if something occurs in the future, I will ping you :-)

I will probably drop the support again in a year, when 7.4 won't be supported with the security fixes.

**Comment by finwe** [comment]
Thanks!
